create release with cargo version

diff --git a/.github/workflows/publish_release.yml b/.github/workflows/publish_release.yml
--- a/.github/workflows/publish_release.yml
+++ b/.github/workflows/publish_release.yml
@@ -3,9 +3,10 @@ name: Publish new Release
 # only trigger on pull request closed events
 on:
   pull_request:
-    types: [ closed ]
+    types: 
+      - closed
   workflow_dispatch:
-     branches:    
+    branches:    
       - master  
 
 jobs:
@@ -24,3 +25,31 @@ jobs:
       
       - name: Checkout
         uses: actions/checkout@v2
+          
+      - name: Cargo Version for text-sanitizer
+        id: cargo_version
+        run: |
+          cargo_version=`scripts/cargo_version.py text-sanitizer | grep -i "text-sanitizer" | cut -d"=" -f2`
+          if [ -z cargo_version ]; then echo "could not find CARGO VERSION"; exit 1; fi;
+          version_tag="v$cargo_version"
+          echo "::set-output name=version::$version_tag"
+          
+      - name: Check Repository for Cargo Version Tag
+        id: git_tag
+        run: |
+          tag_label=`git tag -l "${{ steps.cargo_version.outputs.version }}"`
+          tag_exists=`echo -n "$tag_label" | wc -l`
+          echo "::set-output name=tag::$tag_label name=exists::$tag_exists"
+        
+      - name: Tag the Repository with Cargo Version Tag
+        id: git_tag_set
+        if: steps.git_tag.outputs.exists == 0
+        run: git -a "${{ steps.cargo_version.outputs.version }}" -m "text-sanitizer ${{ steps.cargo_version.outputs.version }} released"       
+          
+      - name: Create Release
+        id: release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: ${{ steps.git_tag.outputs.tag }}
+          token: ${{ secrets.GITHUB_RELEASE_TOKEN }}
+          
